/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.views;

import javax.swing.JOptionPane;
import ws.org.*;
import cl.views.tableModel.ClienteTableModel;
import java.util.List;

/**
 *
 * @author joaov
 */
public class clienteJPanel extends javax.swing.JPanel {
    private List <Cliente> lista;
    private ClienteTableModel tableModel;
    Servidor_Service servico = new Servidor_Service();
    Servidor porta = servico.getServidorPort();
    
    /**
     * Creates new form clienteJPanel
     */
    public clienteJPanel() {     
        List<Cliente> response = porta.listAccount("");
        for (Cliente temp : response) {
			System.out.println(temp);
		}
        tableModel = new ClienteTableModel(response);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idjLabel = new javax.swing.JLabel();
        cpfjLabel = new javax.swing.JLabel();
        nomejLabel = new javax.swing.JLabel();
        ruajLabel = new javax.swing.JLabel();
        bairrojLabel = new javax.swing.JLabel();
        idjTextField = new javax.swing.JTextField();
        cpfjTextField = new javax.swing.JTextField();
        nomejTextField = new javax.swing.JTextField();
        salvarjButton = new javax.swing.JButton();
        cancelarjButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClientejTable = new javax.swing.JTable();
        removerjButton = new javax.swing.JButton();
        editarjButton = new javax.swing.JButton();
        field_senha = new javax.swing.JPasswordField();
        saldoTextField = new javax.swing.JFormattedTextField();

        idjLabel.setText("Id:");

        cpfjLabel.setText("CPF:");

        nomejLabel.setText("Nome:");

        ruajLabel.setText("Saldo:");

        bairrojLabel.setText("Pin:");

        idjTextField.setEditable(false);
        idjTextField.setEnabled(false);
        idjTextField.setFocusCycleRoot(true);

        cpfjTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        nomejTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        salvarjButton.setText("Salvar");
        salvarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarjButtonActionPerformed(evt);
            }
        });

        cancelarjButton.setText("Cancelar");
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Cliente");

        ClientejTable.setModel(tableModel);
        jScrollPane1.setViewportView(ClientejTable);

        removerjButton.setText("Remover");
        removerjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerjButtonActionPerformed(evt);
            }
        });

        editarjButton.setText("Editar");
        editarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarjButtonActionPerformed(evt);
            }
        });

        field_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_senhaActionPerformed(evt);
            }
        });

        saldoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bairrojLabel)
                            .addComponent(ruajLabel)
                            .addComponent(nomejLabel)
                            .addComponent(cpfjLabel)
                            .addComponent(idjLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                            .addComponent(nomejTextField)
                            .addComponent(field_senha)
                            .addComponent(saldoTextField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(salvarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(removerjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(editarjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelarjButton, salvarjButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idjLabel)
                    .addComponent(idjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfjLabel)
                    .addComponent(cpfjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomejLabel)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruajLabel)
                    .addComponent(saldoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(field_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairrojLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarjButton)
                    .addComponent(cancelarjButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removerjButton)
                    .addComponent(editarjButton))
                .addGap(174, 174, 174))
        );

        idjTextField.getAccessibleContext().setAccessibleName("");
        idjTextField.getAccessibleContext().setAccessibleDescription("");
        cpfjTextField.getAccessibleContext().setAccessibleName("");
        cpfjTextField.getAccessibleContext().setAccessibleDescription("");
        nomejTextField.getAccessibleContext().setAccessibleName("");
        nomejTextField.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void salvarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarjButtonActionPerformed
       
        try {
            String resut = porta.addAccount("0",field_senha.getText(), nomejTextField.getText(), cpfjTextField.getText(),Double.parseDouble(saldoTextField.getText()));
            JOptionPane.showMessageDialog(
                salvarjButton, resut);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(
                salvarjButton, "Nao foi possivel salvar");
        }

       

        cancelarjButtonActionPerformed(null);

        ClienteTableModel modelo = (ClienteTableModel) ClientejTable.getModel();

        modelo.fireTableRowsInserted(0, 1);
    }//GEN-LAST:event_salvarjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        idjTextField.setText("");
        cpfjTextField.setText("");
        nomejTextField.setText("");
       saldoTextField.setText("");
       field_senha.setText("");
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void removerjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerjButtonActionPerformed
        int[] linhas = ClientejTable.getSelectedRows();
        for(int linha : linhas){
            Integer user_id =  (Integer)ClientejTable.getModel().getValueAt(ClientejTable.convertRowIndexToModel(linha), 0);     
            String pin =  JOptionPane.showInputDialog("Digite o pin "+Integer.toString(user_id));
            String result = porta.deleteAccount(Integer.toString(user_id), pin);
            
            ClienteTableModel modelo = 
                (ClienteTableModel) ClientejTable.getModel();
        
            modelo.fireTableRowsDeleted(0, 1);
             JOptionPane.showMessageDialog(
                salvarjButton, result);
        }
    }//GEN-LAST:event_removerjButtonActionPerformed

    private void editarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarjButtonActionPerformed
        int linha = ClientejTable.getSelectedRow();

        if (linha >= 0) {
            Cliente selecionado;
           try {
            String resut = porta.addAccount("0",field_senha.getText(), cpfjTextField.getText(),nomejTextField.getText(),Double.parseDouble(saldoTextField.getText()));
            JOptionPane.showMessageDialog(
                salvarjButton, resut);
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(
                    salvarjButton, "Nao foi possivel salvar");
            }

            
            
        } else {
            JOptionPane.showMessageDialog(this, "Selecione 1 registro");
        }
    }//GEN-LAST:event_editarjButtonActionPerformed

    private void saldoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoTextFieldActionPerformed

    private void field_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_senhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClientejTable;
    private javax.swing.JLabel bairrojLabel;
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JLabel cpfjLabel;
    private javax.swing.JTextField cpfjTextField;
    private javax.swing.JButton editarjButton;
    private javax.swing.JPasswordField field_senha;
    private javax.swing.JLabel idjLabel;
    private javax.swing.JTextField idjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JButton removerjButton;
    private javax.swing.JLabel ruajLabel;
    private javax.swing.JFormattedTextField saldoTextField;
    private javax.swing.JButton salvarjButton;
    // End of variables declaration//GEN-END:variables
}
